backend:
  name: git-gateway
  branch: main

publish_mode: simple
media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "posts"
    label: "Artigos do Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Imagem de capa", name: "cover", widget: "image", required: false }
      - { label: "Resumo (aparece na listagem do blog)", name: "excerpt", widget: "text" }
      - { label: "Texto do artigo", name: "body", widget: "markdown" }
